version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
  service:
    build: ./petmony
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./auth_service:/app
    ports:
      - "8000:8000"
    depends_on:
      - db